# One CLI to format the code tree - https://github.com/numtide/treefmt

formatters = ["deadnix", "nixfmt-rfc-style"]

[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
excludes = []
includes = ["*.nix"]

[formatter.nixfmt-rfc-style]
command = "nixfmt"
options = []
includes = ["*.nix"]
excludes = []
